# Adds namespace to all resources.
namespace: default

# Value of this field is prepended to the
# names of all resources, e.g. a deployment named
# "wordpress" becomes "alices-wordpress".
# Note that it should also match with the prefix (text before '-') of the namespace
# field above.
namePrefix: l6p-

# Labels to add to all resources and selectors.
commonLabels:
  l6p-app: ui-web

resources:
- deployment.yaml
- service.yaml
- service_account.yaml
- ingress.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: img
  newName: localhost:32000/ui-web
  newTag: latest
